# Generated by Django 5.0.2 on 2024-02-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_featured_img_course_techs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descripton',
            new_name='description',
        ),
    ]
