# Generated by Django 5.0.2 on 2024-03-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studentassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignment',
            old_name='detail',
            new_name='description',
        ),
    ]
