# Generated by Django 5.0.2 on 2024-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_student_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
