# Generated by Django 5.0.2 on 2024-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField()),
                ('notification_for', models.CharField(max_length=200)),
                ('notification_created_time', models.DateTimeField(auto_now_add=True)),
                ('notification_read_status', models.BooleanField(default=False)),
            ],
        ),
    ]
