# Generated by Django 5.0.2 on 2024-03-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notification'},
        ),
    ]
