# Generated by Django 5.0.2 on 2024-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_notification_notification_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
