# Generated by Django 5.0.2 on 2024-03-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_coursequiz_options_alter_quizquestions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequiz',
            name='assign_status',
        ),
    ]
